{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubewhisperer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewhisperer.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN:      {{ .Values.secrets.githubToken | quote }}
  PROMETHEUS_TOKEN:  {{ .Values.secrets.prometheusToken | quote }}
  OTEL_TOKEN:        {{ .Values.secrets.otelToken | quote }}
  LOKI_TOKEN:        {{ .Values.secrets.lokiToken | quote }}
{{- end }}
