import { useState } from "react";
import ROADMAP_DATA from "./roadmap.json";

// ── constants ──────────────────────────────────────────────────────────────────

const GITHUB = "https://github.com/a1h8/kube-verdict";
const GIF_URL =
  "https://raw.githubusercontent.com/a1h8/kube-verdict/main/demo/demo_kubeWhisperer.gif";

const SCENARIOS = [
  {
    id: "h001",
    title: "CrashLoopBackOff",
    desc: "Missing dependency. BFS graph traversal, BM25+FAISS retrieval, anchor detection, confidence scoring.",
  },
  {
    id: "h002",
    title: "ImagePullBackOff",
    desc: "Registry auth / tag drift. Helm drift detection, drift.* annotations, image proposal generation.",
  },
  {
    id: "h003",
    title: "OOMKilled",
    desc: "Memory limit drift. Helm declared-vs-observed diff, anchor_fix_hints() → helm upgrade --set.",
  },
  {
    id: "h004",
    title: "Missing ConfigMap / Secret",
    desc: "Resource missing at pod start. DeploymentReadinessDetector, missing.* annotations, kubectl create hints.",
  },
  {
    id: "h005",
    title: "RBAC — missing ClusterRoleBinding",
    desc: "SA exists but no binding. Detected via SA→role graph, kubectl create clusterrolebinding hint.",
  },
  {
    id: "h006",
    title: "NetworkPolicy egress block",
    desc: "Blocked egress traffic. netpol.* annotations, kubectl edit networkpolicy hints.",
  },
  {
    id: "h007",
    title: "HPA cannot scale — metrics-server unavailable",
    desc: "HPA target resolution, metrics-unavailable detection, metrics-server fix hints.",
  },
  {
    id: "h008",
    title: "Init container failing — DB migration exits 1",
    desc: "Init:0/1 detection, init-container log correlation, migration-failure root cause.",
  },
  {
    id: "h009",
    title: "Liveness probe too aggressive",
    desc: "Probe-timeout drift (timeoutSeconds declared vs deployed) → helm upgrade fix.",
  },
  {
    id: "h010",
    title: "ResourceQuota exceeded — pod Pending",
    desc: "ResourceQuota entity, namespace quota correlation, pending-pod root cause.",
  },
];

const PIPELINE_STEPS = [
  "K8s events + Prometheus + OTel/Loki + Helm values",
  "Ontology graph + anchor drift detection",
  "BM25 + FAISS + RRF hybrid retrieval",
  "Beam-search hypothesis ranking",
  "LLM root-cause analysis (evidence-grounded)",
  "Dry-run validation → human review gate → GitOps patch",
];

const LIMITATIONS = [
  "Validated cases: h001–h010 proven end-to-end in CI; h011 (StatefulSet PVC) is an open contribution, not yet shipped.",
  "Single-cluster — multi-cluster not yet wired end-to-end.",
  "No auto-remediation in production — human approval gate is by design.",
  "LLM performance is local-hardware-dependent — Mistral via Ollama requires at least 8 GB RAM; a GPU significantly accelerates inference.",
  "No real-time alerting integration — Prometheus and Loki are pulled on demand, not streamed.",
];

const INCIDENT_SUMMARY = `════════════════════════════════════════════════════════════
  INCIDENT SUMMARY
════════════════════════════════════════════════════════════
  Severity    : HIGH
  Namespace   : kubeverdict-demo
  Confidence  : MEDIUM
  Impacted    : payment-service, ml-inference, notification-service

  Root cause  :
    payment-service is in CrashLoopBackOff due to repeated
    container failures. ml-inference cannot pull its image
    (ImagePullBackOff). notification-service is missing a
    required environment variable.

  Key evidence:
    • [447×] BackOff on Pod/payment-service-58555ff9b6-4bxv2
      "Back-off restarting failed container payment-service"
    • [  1×] Failed on Pod/ml-inference-6c7dbf6d5f-2nlsr
      "Failed to pull image: not found"

  Proposed fix:
    $ kubectl rollout restart deployment/payment-service
    $ kubectl set image deployment/ml-inference \\
        ml-inference=<correct-image>
════════════════════════════════════════════════════════════
  Approve and apply remediation? [approve/reject]: approve
  ✓ Remediation approved — commands above should be applied.`;

// ── roadmap data (generated by tools/roadmap.py) ──────────────────────────────

const ROADMAP_BLOCS = ROADMAP_DATA.blocs;
const ROADMAP_DATE  = new Date(ROADMAP_DATA.generated_at).toLocaleDateString("en-US", {
  year: "numeric", month: "short", day: "numeric",
});

// ── style helpers ──────────────────────────────────────────────────────────────

const T = {
  page: {
    minHeight: "100vh",
    background: "#0f172a",
    color: "#e2e8f0",
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  wrap: { maxWidth: 860, margin: "0 auto", padding: "0 1.5rem" },
  section: { padding: "4rem 0" },
  h2: { fontSize: 22, fontWeight: 700, color: "#f1f5f9", marginBottom: 8 },
  sub: { fontSize: 14, color: "#64748b", marginBottom: 32 },
  card: {
    background: "#1e293b",
    borderRadius: 10,
    padding: "20px 24px",
  },
  badge: {
    display: "inline-block",
    fontSize: 11,
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: 4,
    background: "#0f172a",
    color: "#38bdf8",
    border: "1px solid #1e3a5f",
    marginBottom: 8,
  },
};


function Btn({ href, children, primary, external = true }) {
  const [hovered, setHovered] = useState(false);
  return (
    <a
      href={href}
      {...(external ? { target: "_blank", rel: "noopener noreferrer" } : {})}
      style={{
        display: "inline-block",
        padding: "10px 22px",
        borderRadius: 8,
        fontSize: 14,
        fontWeight: 600,
        textDecoration: "none",
        background: primary ? "#3b82f6" : "#1e293b",
        color: primary ? "#fff" : "#94a3b8",
        border: primary ? "none" : "1px solid #334155",
        opacity: hovered ? 0.85 : 1,
        transition: "opacity 0.15s",
      }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {children}
    </a>
  );
}

// ── sections ───────────────────────────────────────────────────────────────────

function Hero() {
  return (
    <div
      style={{
        ...T.section,
        borderBottom: "1px solid #1e293b",
        paddingBottom: "3rem",
      }}
    >
      <div style={T.wrap}>
        <div style={{ ...T.badge, marginBottom: 16 }}>
          Open-source Kubernetes RCA & Remediation Copilot
        </div>
        <h1
          style={{
            fontSize: 36,
            fontWeight: 800,
            color: "#f1f5f9",
            lineHeight: 1.2,
            marginBottom: 16,
          }}
        >
          KubeVerdict
        </h1>
        <p
          style={{
            fontSize: 18,
            color: "#94a3b8",
            marginBottom: 8,
            maxWidth: 620,
            lineHeight: 1.6,
          }}
        >
          AI-assisted Kubernetes incident analysis with evidence-grounded RCA
          and human-gated remediation.
        </p>
        <p
          style={{
            fontSize: 14,
            color: "#475569",
            marginBottom: 32,
            maxWidth: 580,
          }}
        >
          Correlates Kubernetes events, Helm drift, Prometheus alerts, OTel
          traces and Loki logs to reduce incident investigation time.
        </p>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
          <Btn href="#demo" primary external={false}>
            Watch demo
          </Btn>
          <Btn href={GITHUB}>View GitHub</Btn>
          <Btn href={`${GITHUB}/blob/main/docs/test-cases.md`}>
            Run offline test cases
          </Btn>
        </div>
      </div>
    </div>
  );
}

function WhyItMatters() {
  return (
    <div style={{ ...T.section, borderBottom: "1px solid #1e293b" }}>
      <div style={T.wrap}>
        <h2 style={T.h2}>Why it matters</h2>
        <p
          style={{
            fontSize: 15,
            color: "#94a3b8",
            lineHeight: 1.7,
            maxWidth: 680,
          }}
        >
          Most Kubernetes outages are not caused by a single failing pod. When
          payment-service crashes, the on-call engineer opens five tabs
          simultaneously: pod logs, Kubernetes events, Helm history, Prometheus
          graphs, and the GitOps repo — at 2 AM, under pressure, with three
          Slack threads open. The root cause is rarely where the alert fired.
          <br />
          <br />
          KubeVerdict reduces that cognitive load. It correlates signals into
          a single evidence-grounded root cause analysis, ranked by confidence,
          with a human approval gate before any remediation command touches
          production.
        </p>
      </div>
    </div>
  );
}

function DemoSection() {
  return (
    <div
      id="demo"
      style={{ ...T.section, borderBottom: "1px solid #1e293b" }}
    >
      <div style={T.wrap}>
        <h2 style={T.h2}>What the output looks like</h2>
        <p style={T.sub}>
          Five services down simultaneously. KubeVerdict identifies each root
          cause independently, ranked by evidence weight.
        </p>

        <pre
          style={{
            background: "#020617",
            border: "1px solid #1e293b",
            borderRadius: 10,
            padding: "20px 24px",
            fontSize: 12.5,
            lineHeight: 1.7,
            color: "#94a3b8",
            overflowX: "auto",
            marginBottom: 32,
            whiteSpace: "pre",
          }}
        >
          {INCIDENT_SUMMARY}
        </pre>

        <img
          src={GIF_URL}
          alt="KubeVerdict demo"
          style={{
            width: "100%",
            borderRadius: 10,
            border: "1px solid #1e293b",
          }}
        />
      </div>
    </div>
  );
}

function Scenarios() {
  return (
    <div style={{ ...T.section, borderBottom: "1px solid #1e293b" }}>
      <div style={T.wrap}>
        <h2 style={T.h2}>Validated scenarios</h2>
        <p style={T.sub}>
          Ten failure patterns proven end-to-end in CI — no cluster, no LLM
          required.
        </p>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
            gap: 16,
          }}
        >
          {SCENARIOS.map((s) => (
            <div key={s.id} style={T.card}>
              <div style={{ ...T.badge, marginBottom: 8 }}>{s.id}</div>
              <div
                style={{
                  fontSize: 15,
                  fontWeight: 700,
                  color: "#f1f5f9",
                  marginBottom: 8,
                }}
              >
                {s.title}
              </div>
              <div style={{ fontSize: 12.5, color: "#64748b", lineHeight: 1.6 }}>
                {s.desc}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function HowItWorks() {
  return (
    <div style={{ ...T.section, borderBottom: "1px solid #1e293b" }}>
      <div style={T.wrap}>
        <h2 style={T.h2}>How it works</h2>
        <p style={T.sub}>
          The LLM is constrained by retrieved evidence — deterministic signals
          rank hypotheses first.
        </p>
        <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
          {PIPELINE_STEPS.map((step, i) => (
            <div
              key={i}
              style={{ display: "flex", alignItems: "flex-start", gap: 16 }}
            >
              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                }}
              >
                <div
                  style={{
                    width: 28,
                    height: 28,
                    borderRadius: "50%",
                    background: "#1e293b",
                    border: "2px solid #334155",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: 11,
                    fontWeight: 700,
                    color: "#38bdf8",
                    flexShrink: 0,
                  }}
                >
                  {i + 1}
                </div>
                {i < PIPELINE_STEPS.length - 1 && (
                  <div
                    style={{
                      width: 1,
                      height: 24,
                      background: "#1e3a5f",
                      margin: "2px 0",
                    }}
                  />
                )}
              </div>
              <div
                style={{
                  fontSize: 14,
                  color: "#94a3b8",
                  paddingTop: 5,
                  paddingBottom: i < PIPELINE_STEPS.length - 1 ? 0 : 0,
                  lineHeight: 1.5,
                }}
              >
                {step}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function Limitations() {
  return (
    <div style={{ ...T.section, borderBottom: "1px solid #1e293b" }}>
      <div style={T.wrap}>
        <h2 style={T.h2}>Current limitations</h2>
        <p style={T.sub}>
          These constraints are known and intentional — not hidden.
        </p>
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {LIMITATIONS.map((l, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                gap: 12,
                fontSize: 14,
                color: "#64748b",
                lineHeight: 1.6,
              }}
            >
              <span style={{ color: "#fb923c", flexShrink: 0, marginTop: 1 }}>
                →
              </span>
              {l}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

const STATUS_META = {
  DONE:        { label: "DONE",        color: "#21c354", bg: "#052e16" },
  IN_PROGRESS: { label: "IN PROGRESS", color: "#facc15", bg: "#1c1a05" },
  TODO:        { label: "TODO",        color: "#475569", bg: "#0f172a" },
};

function Roadmap() {
  const done = ROADMAP_BLOCS.filter((b) => b.status === "DONE").length;
  const total = ROADMAP_BLOCS.length;

  return (
    <div style={{ ...T.section, borderBottom: "1px solid #1e293b" }}>
      <div style={T.wrap}>
        <h2 style={T.h2}>Roadmap</h2>
        <p style={T.sub}>
          Checked on each deploy by <code>tools/roadmap.py</code>. {done}/{total} blocs
          complete. Last run: {ROADMAP_DATE}.
        </p>

        <div style={{ display: "grid", gap: 12 }}>
          {ROADMAP_BLOCS.map((bloc) => {
            const meta    = STATUS_META[bloc.status];
            const passed  = bloc.checks.filter((c) => c.done).length;
            return (
              <div
                key={bloc.id}
                style={{
                  ...T.card,
                  borderLeft: `3px solid ${meta.color}`,
                }}
              >
                <div
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    justifyContent: "space-between",
                    gap: 12,
                    marginBottom: 10,
                  }}
                >
                  <div>
                    <span style={{ fontSize: 11, color: "#64748b", fontWeight: 600 }}>
                      {bloc.id}
                    </span>
                    <span
                      style={{
                        fontSize: 15,
                        fontWeight: 700,
                        color: "#f1f5f9",
                        marginLeft: 10,
                      }}
                    >
                      {bloc.title}
                    </span>
                  </div>
                  <span
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      padding: "2px 8px",
                      borderRadius: 4,
                      color: meta.color,
                      background: meta.bg,
                      border: `1px solid ${meta.color}33`,
                      whiteSpace: "nowrap",
                      flexShrink: 0,
                    }}
                  >
                    {meta.label}
                  </span>
                </div>

                <p style={{ fontSize: 12, color: "#64748b", marginBottom: 10 }}>
                  {bloc.description}
                </p>

                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px 16px" }}>
                  {bloc.checks.map((chk) => (
                    <div
                      key={chk.label}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: 6,
                        fontSize: 12,
                        color: chk.done ? "#94a3b8" : "#475569",
                      }}
                    >
                      <span style={{ color: chk.done ? "#21c354" : "#ef4444", flexShrink: 0 }}>
                        {chk.done ? "✓" : "✗"}
                      </span>
                      {chk.label}
                    </div>
                  ))}
                </div>

                {bloc.status !== "DONE" && (
                  <div style={{ fontSize: 11, color: "#475569", marginTop: 10 }}>
                    {passed}/{bloc.checks.length} checks passing
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

function Footer() {
  return (
    <div style={{ padding: "2rem 0" }}>
      <div
        style={{
          ...T.wrap,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: 12,
        }}
      >
        <span style={{ fontSize: 12, color: "#334155" }}>
          KubeVerdict — Open-source Kubernetes RCA & Remediation Copilot. Apache 2.0.
        </span>
        <div style={{ display: "flex", gap: 16 }}>
          <a
            href={GITHUB}
            target="_blank"
            rel="noopener noreferrer"
            style={{ fontSize: 12, color: "#475569", textDecoration: "none" }}
          >
            GitHub
          </a>
          <a
            href={`${GITHUB}/blob/main/docs/architecture.md`}
            target="_blank"
            rel="noopener noreferrer"
            style={{ fontSize: 12, color: "#475569", textDecoration: "none" }}
          >
            Architecture
          </a>
          <a
            href={`${GITHUB}/blob/main/docs/api.md`}
            target="_blank"
            rel="noopener noreferrer"
            style={{ fontSize: 12, color: "#475569", textDecoration: "none" }}
          >
            REST API
          </a>
          <a
            href={`${GITHUB}/blob/main/docs/roadmap.md`}
            target="_blank"
            rel="noopener noreferrer"
            style={{ fontSize: 12, color: "#475569", textDecoration: "none" }}
          >
            Roadmap
          </a>
        </div>
      </div>
    </div>
  );
}

// ── app ────────────────────────────────────────────────────────────────────────

export default function App() {
  return (
    <div style={T.page}>
      <Hero />
      <WhyItMatters />
      <DemoSection />
      <Scenarios />
      <HowItWorks />
      <Limitations />
      <Roadmap />
      <Footer />
    </div>
  );
}
